name: game_center
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.12

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  localization: ^2.1.0
  flutter_bloc: ^8.1.2
  flutter_localization: ^0.1.10
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_flavorizr: ^2.1.5
  floor: ^1.4.1
  flutter_keyboard_visibility: ^5.4.0
  firebase_core: ^2.5.0
  change_app_package_name: ^1.1.0
  firebase_remote_config: ^3.0.10
  socket_io_client: ^2.0.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  mockito: ^5.0.10
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.2
  floor_generator: ^1.2.0
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    prod:
      app:
        name: "Game Center App Prod"

      android:
        applicationId: "game.center.prod"
        firebase:
          config: ".config/firebase/prod/google-services.json"

      ios:
        bundleId: "game.center.prod"
        firebase:
          config: ".config/firebase/prod/GoogleService-Info.plist"

    qc:
      app:
        name: "Game Center App qc"

      android:
        applicationId: "game.center.qc"
        firebase:
          config: ".config/firebase/qc/google-services.json"

      ios:
        bundleId: "game.center.qc"
        firebase:
          config: ".config/firebase/qc/GoogleService-Info.plist"
