// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodYWk-9CNynQ9L7XgdFtN_gKwP1njD1c',
    appId: '1:922479036460:android:3eff4ccdd88e0ea6bbe989',
    messagingSenderId: '922479036460',
    projectId: 'gamecenter-b2951',
    storageBucket: 'gamecenter-b2951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEs52jVGU9ThxHyuCtirajGtpTIekC_Kc',
    appId: '1:922479036460:ios:29b33feb3d756c60bbe989',
    messagingSenderId: '922479036460',
    projectId: 'gamecenter-b2951',
    storageBucket: 'gamecenter-b2951.appspot.com',
    androidClientId: '922479036460-6l9kmasjdfbh46ockp4j1003ie330nck.apps.googleusercontent.com',
    iosClientId: '922479036460-hochg0s8vkv15il8sfn2e4pvben7ug7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameCenter',
  );
}
